// The background music was generated by an algorithm that I cannot remember in december 2022 (probaly Mubert)
// The prompt by Benjamin Molinet was something like "background music; chill; videogame; loop"
// I found back some alternatives like OpenAI Jukebox, Google musicLM, and Mubert.
// There is only a small problem with the file, the sound volume is higher for 1 second...

// Initialize audio context
let audioContext;

// Get audio element from HTML
const audioElement = document.getElementById('background-music');

// Create audio source and connect to destination
function initAudioContext() {
    audioContext = new (window.AudioContext || window.webkitAudioContext)();

    const audioSource = audioContext.createMediaElementSource(audioElement);
    audioSource.connect(audioContext.destination);
}

// Play audio
function playAudio() {
    if (!audioContext) {
        initAudioContext();
    }
    audioContext.resume();
    audioElement.play();
}

// Pause audio
function pauseAudio() {
    audioElement.pause();
}

// Set audio loop
function setLoop(loop) {
    audioElement.loop = loop;
}

// Set audio volume
function setVolume(volume) {
    audioElement.volume = volume;
}

// Start playing audio on button click
const playButton = document.getElementById('play-button');
playButton.addEventListener('click', () => {
    playAudio();
    setVolume(volumeSlider.value); 
    setLoop(true);
});

// Pause playing audio on button click
const pauseButton = document.getElementById('pause-button');
pauseButton.addEventListener('click', () => {
    pauseAudio();
});

// Handle volume change from the slider
const volumeSlider = document.getElementById('volume-slider');
volumeSlider.addEventListener('input', (event) => {
    const volume = event.target.value;
    setVolume(volume);
});